site_name: Pterodactyl PHP SDK
theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: true
    
repo_name: hcgcloud/pterodactyl-sdk
repo_url: https://github.com/hcgcloud/pterodactyl-sdk
edit_uri: 'https://github.com/hcgcloud/pterodactyl-sdk-docs/edit/master/docs'

google_analytics: 
  - 'UA-131385947-5'
  - 'auto'

nav:
  - 'Home':
    - 'Welcome': index.md
    - 'Getting Started': getting-started.md
    - 'Resources': resources.md
    - 'Exceptions': exceptions.md
    - 'References': references.md
  - 'Client':
    - 'List servers': client/list-servers.md
    - 'Get server': client/get-server.md
    - 'Power server': client/power-server.md
    - 'Command server': client/command-server.md
    - 'Utilization server': client/utilization-server.md
  - 'Application':
    - 'Server':
      - 'List servers': application/server/servers.md
      - 'Get server': application/server/server.md
      - 'Get server by external id': application/server/server-ex.md
      - 'Create server': application/server/create-server.md
      - 'Delete server': application/server/delete-server.md
      - 'Force delete server': application/server/force-delete-server.md
      - 'Suspend server': application/server/suspend-server.md
      - 'Unsuspend server': application/server/unsuspend-server.md
      - 'Reinstall server': application/server/reinstall-server.md
      - 'Rebuild server': application/server/rebuild-server.md
      - 'Update server details': application/server/update-server-details.md
      - 'Update server build': application/server/update-server-build.md
      - 'Update server startup': application/server/update-server-startup.md
    - 'User':
      - 'List users': application/user/users.md
      - 'Get user': application/user/user.md
      - 'Get user by external id': application/user/user-ex.md
      - 'Create user': application/user/create-user.md
      - 'Update user': application/user/update-user.md
      - 'Delete user': application/user/delete-user.md
    - 'Node':
      - 'List nodes': application/node/nodes.md
      - 'Get node': application/node/node.md
      - 'Create node': application/node/create-node.md
      - 'Update node': application/node/update-node.md
      - 'Delete node': application/node/delete-node.md
    - 'Allocation':
      - 'List allocations': application/allocation/allocations.md
    - 'Nest':
      - 'List nests': application/nest/nests.md
      - 'Get nest': application/nest/nest.md
    - 'Egg':
      - 'List eggs': application/egg/eggs.md
      - 'Get egg': application/egg/egg.md

plugins:
  - search
  - minify:
      minify_html: true

extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/hcgcloud'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true