site_name: Pterodactyl PHP SDK
theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: true
    
repo_name: hcgcloud/pterodactyl-sdk
repo_url: https://github.com/hcgcloud/pterodactyl-sdk
edit_uri: 'https://github.com/hcgcloud/pterodactyl-sdk-docs/edit/master/docs'

nav:    
  - 'Home':
    - 'Welcome': index.md
    - 'Getting Started': getting-started.md
    - 'Resources': resources.md
    - 'Exceptions': exceptions.md
  - 'Client':
    - 'List servers': client/list-servers.md
    - 'Get server': client/get-server.md
    - 'Power server': client/power-server.md
    - 'Command server': client/command-server.md
    - 'Utilization server': client/utilization-server.md
  - 'Application':
    - 'Server':
      - 'List servers': application/server/servers.md
      - 'Get server': application/server/server.md
      - 'Get server by external id': application/server/server-ex.md
      - 'Create server': application/server/create-server.md
      - 'Delete server': application/server/delete-server.md
      - 'Force delete server': application/server/force-delete-server.md
      - 'Suspend server': application/server/suspend-server.md
      - 'Unsuspend server': application/server/unsuspend-server.md
      - 'Reinstall server': application/server/reinstall-server.md
      - 'Rebuild server': application/server/rebuild-server.md
      - 'Update server details': application/server/update-server-details.md
      - 'Update server build': application/server/update-server-build.md
      - 'Update server startup': application/server/update-server-startup.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true